backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: 'src/assets/images'

collections:
  # Existing post collection (updated path to src/data/post)
  - name: 'post'
    label: 'Post'
    folder: 'src/data/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, field: { label: 'Tag', name: 'tag', widget: 'string' } }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  # New collection for src/content/config.ts (fixed to use files array)
  - name: 'content_config'
    label: 'Content Config'
    files:
      - file: 'src/content/config.ts'
        label: 'Content Config'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Ignore Title Template', name: 'ignoreTitleTemplate', widget: 'boolean', required: false }
      - { label: 'Canonical URL', name: 'canonical', widget: 'string', required: false }
      - { 
          label: 'Robots', 
          name: 'robots', 
          widget: 'object', 
          fields: [
            { label: 'Index', name: 'index', widget: 'boolean', required: false },
            { label: 'Follow', name: 'follow', widget: 'boolean', required: false }
          ]
        }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { 
          label: 'Open Graph', 
          name: 'openGraph', 
          widget: 'object', 
          fields: [
            { label: 'URL', name: 'url', widget: 'string', required: false },
            { label: 'Site Name', name: 'siteName', widget: 'string', required: false },
            { 
              label: 'Images', 
              name: 'images', 
              widget: 'list', 
              fields: [
                { label: 'URL', name: 'url', widget: 'string' },
                { label: 'Width', name: 'width', widget: 'number', required: false },
                { label: 'Height', name: 'height', widget: 'number', required: false }
              ]
            },
            { label: 'Locale', name: 'locale', widget: 'string', required: false },
            { label: 'Type', name: 'type', widget: 'string', required: false }
          ]
        }
      - { 
          label: 'Twitter', 
          name: 'twitter', 
          widget: 'object', 
          fields: [
            { label: 'Handle', name: 'handle', widget: 'string', required: false },
            { label: 'Site', name: 'site', widget: 'string', required: false },
            { label: 'Card Type', name: 'cardType', widget: 'string', required: false }
          ]
        }

  # New collection for src/data/ (general data files)
  - name: 'data_files'
    label: 'Data Files'
    folder: 'src/data'
    create: true
    filter: { field: 'name', value: 'post', comparison: 'doesNotEqual' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
